LOOPS = advancedClassificationLoop.o
RECUR = advancedClassificationRecursion.o
FLAGS = -Wall -g



all: libclassloops.a libclassloops.so libclassrec.a libclassrec.so mains maindloop maindrec

loops : libclassloops.a
libclassloops.a: main.o libclassloops.a 
	ar -rcs libclassloops.a $(LOOPS)

recursives: libclassrec.a
libclassrec.a : main.o libclassrec.a
	ar -rcs libclassrec.so $(RECUR)

loopd: libclassloops.so  
libclassloops.so : main.o libclassloops.so
	gcc -shared -o libclassloops.a $(LOOPS)

recursived : libclassrec.so
libclassrec.so : main.o libclassrec.so
	gcc -shared -o libclassrec.so $(RECUR)

mains: main.o  libclassrec.a
	$(FLAGS) -o mains main.o libclassrec.a

maindloop: main.o  libclassloops.so
	$(FLAGS) -o maindloop main.o libclassloops.so

maindrec: main.o  libclassrec.so
	$(FLAGS) -o maindrec main.o libclassrec.so

.PHONY: clean all

clean:
	rm -f  *.o *.a *.so loops recursives loopd recursived

